src/Entity/Employee.php
<?php

namespace App\Entity;

use App\Repository\EmployeeRepository;
use DateTime;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

/**
 * The employee entity that contains all data
 */
#[ORM\Entity(repositoryClass: EmployeeRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_USERNAME_EMPLOYEE', fields: ['username'])]
class Employee extends AbstractEntity
{


    /**
     * The username of the user
     */
    #[ORM\Column(length: 255)]
    private ?string $username = null;

    /**
     * The firstname of the user
     */
    #[ORM\Column(length: 255)]
    private ?string $firstName = null;

    /**
     * The lastname of the user
     */
    #[ORM\Column(length: 255)]
    private ?string $lastName = null;

    /**
     * The target working hours
     */
    #[ORM\Column(nullable: true)]
    private ?float $targetWorkingHours = null;

    /**
     * The amount of holidays the user has
     */
    #[ORM\Column(options: ["default" => 0])]
    private ?int $holidays = null;

    /**
     * If the employee is time employed
     */
    #[ORM\Column(nullable: false, options: ["default" => false])]
    private bool $isTimeEmployed = false;

    /**
     * All working periods of the user
     */
    #[ORM\OneToMany(targetEntity: WorktimePeriod::class, mappedBy: 'employee')]
    private Collection $periods;

    /**
     * All special worktime days
     */
    #[ORM\OneToMany(targetEntity: WorktimeSpecialDay::class, mappedBy: 'employee')]
    private Collection $worktimeSpecialDays;

    #[ORM\OneToMany(targetEntity: SpecialDayRequest::class, mappedBy: 'employee')]
    private Collection $specialDayRequests;

    /**
     * All configured worktimes
     */
    #[ORM\OneToMany(targetEntity: ConfiguredWorktime::class, mappedBy: 'employee', cascade: ["persist"])]
    private Collection $configuredWorktimes;

    /**
     * @deprecated Now $transfers is used for determination of overtime
     */
    #[ORM\Column(updatable: false, options: ["default" => 0])]
    private float $overtime = 0;

    /**
     * @deprecated Now $transfers is used for determination of overtime
     */
    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true, updatable: false)]
    private ?DateTimeInterface $overtimeLastUpdate = null;

    #[ORM\Column(type: Types::TIME_MUTABLE, nullable: true)]
    private ?DateTimeInterface $autoLogoutThreshold = null;

    #[ORM\Column(type: Types::JSON, nullable: true)]
    private ?array $overtimeTransfers = [];

    #[ORM\Column(type: Types::FLOAT, nullable: true)]
    private ?float $holidayTransfers = 0;

    public function __construct() {
        $this->periods = new ArrayCollection();
        $this->worktimeSpecialDays = new ArrayCollection();
        $this->configuredWorktimes = new ArrayCollection();
        $this->specialDayRequests = new ArrayCollection();
    }

    /**
     * Gets the username
     *
     * @return string|null The username
     */
    public function getUsername(): ?string
    {
        return $this->username;
    }

    /**
     * Sets the username
     *
     * @param string $username The new username
     * @return $this The updated entity
     */
    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * Gets the firstname
     *
     * @return string|null The firstname
     */
    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    /**
     * Sets the firstname
     *
     * @param string $firstName The new firstname
     * @return $this The updated entity
     */
    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    /**
     * Gets the lastname
     *
     * @return string|null The lastname
     */
    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    /**
     * Sets the lastname
     *
     * @param string $lastName The new lastname
     * @return $this The updated entity
     */
    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * Gets the target working hours
     *
     * @return float|null The target hours
     */
    public function getTargetWorkingHours(): ?float
    {
        return $this->targetWorkingHours;
    }

    /**
     * Sets the target working hours
     *
     * @param float $targetWorkingHours The target hours
     * @return $this The updated entity
     */
    public function setTargetWorkingHours(?float $targetWorkingHours): self
    {
        $this->targetWorkingHours = $targetWorkingHours;

        return $this;
    }

    /**
     * Gets is time employed
     *
     * @return bool is time employed
     */
    public function isTimeEmployed(): bool
    {
        return $this->isTimeEmployed;
    }

    /**
     * Sets is time employed
     *
     * @param bool $isTimeEmployed Is time employed
     * @return $this The updated entity
     */
    public function setIsTimeEmployed(bool $isTimeEmployed): self
    {
        $this->isTimeEmployed = $isTimeEmployed;
        return $this;
    }

    /**
     * Gets all periods
     *
     * @return Collection<WorktimePeriod> All periods
     */
    public function getPeriods(): Collection
    {
        return $this->periods;
    }

    /**
     * Adds a new period to employee
     *
     * @param WorktimePeriod $period The new period
     * @return $this The updated entity
     */
    public function addPeriod(WorktimePeriod $period): self {
        if (!$this->periods->contains($period)) {
            $this->periods->add($period);
        }
        return $this;
    }

    /**
     * Removes a period from employee
     *
     * @param WorktimePeriod $period The period that should be removed
     * @return $this The updated entity
     */
    public function removePeriod(WorktimePeriod $period): self {
        if ($this->periods->contains($period)) {
            $this->periods->removeElement($period);
        }
        return $this;
    }

    /**
     * Gets the holidays of the user
     *
     * @return int|null The amount of holidays
     */
    public function getHolidays(): ?int
    {
        return $this->holidays;
    }

    /**
     * Sets the holidays of the user
     *
     * @param int $holidays The amount of holidays
     * @return $this The updated entity
     */
    public function setHolidays(int $holidays): self {
        $this->holidays = $holidays;
        return $this;
    }

    /**
     * Gets all worktime special days
     *
     * @return Collection The collection
     */
    public function getWorktimeSpecialDays(): Collection {
        return $this->worktimeSpecialDays;
    }

    /**
     * Adds a new special day
     *
     * @param WorktimeSpecialDay $worktimeSpecialDay The special day
     * @return $this The updated entity
     */
    public function addWorktimeSpecialDay(WorktimeSpecialDay $worktimeSpecialDay): self {
        if (!$this->worktimeSpecialDays->contains($worktimeSpecialDay)) {
            $this->worktimeSpecialDays->add($worktimeSpecialDay);
        }
        return $this;
    }

    /**
     * Removes a special worktime day
     *
     * @param WorktimeSpecialDay $worktimeSpecialDay The special day to remove
     * @return $this The updated entity
     */
    public function removeWorktimeSpecialDay(WorktimeSpecialDay $worktimeSpecialDay): self {
        if ($this->worktimeSpecialDays->contains($worktimeSpecialDay)) {
            $this->worktimeSpecialDays->removeElement($worktimeSpecialDay);
        }
        return $this;
    }

    /**
     * Gets all leftover holidays
     *
     * @return int|null All left holidays
     */
    public function getHolidaysLeft(): ?int
    {
        if ($this->getHolidays()) {
            $existingHolidays = $this->getWorktimeSpecialDays()
                ->filter(
                    fn (WorktimeSpecialDay $d) =>
                        $d->getDate()->format("Y") === (new DateTime())->format("Y")
                        && $d->getReason() === WorktimeSpecialDay::REASON_HOLIDAY
                );
            return $this->getHolidays() - $existingHolidays->count();
        }
        return null;
    }

    /**
     * Gets the configured worktimes
     *
     * @return Collection The worktimes
     */
    public function getConfiguredWorktimes(): Collection
    {
        return $this->configuredWorktimes;
    }

    /**
     * Sets the configured worktimes
     *
     * @param Collection $worktimes The worktimes
     * @return $this The updated entity
     */
    public function setConfiguredWorktimes(Collection $worktimes): self
    {
        $this->configuredWorktimes = $worktimes;
        return $this;
    }

    /**
     * Adds a new configured worktime
     *
     * @param ConfiguredWorktime $configuredWorktime The new time
     * @return $this The updated entity
     */
    public function addConfiguredWorktime(ConfiguredWorktime $configuredWorktime): self
    {
        $this->configuredWorktimes->add($configuredWorktime);
        return $this;
    }

    /**
     * Removes a configured worktime
     *
     * @param ConfiguredWorktime $configuredWorktime The removed worktime
     * @return $this The updated entity
     */
    public function removeConfiguredWorktime(ConfiguredWorktime $configuredWorktime): self
    {
        if ($this->configuredWorktimes->contains($configuredWorktime)) {
            $this->configuredWorktimes->removeElement($configuredWorktime);
        }
        return $this;
    }

    /**
     * Gets the auto logout threshold
     *
     * @return DateTimeInterface|null logout threshold
     */
    public function getAutoLogoutThreshold(): ?DateTimeInterface
    {
        return $this->autoLogoutThreshold;
    }

    /**

src/Entity/WorktimePeriod.php
<?php

namespace App\Entity;

use App\Repository\WorktimePeriodRepository;
use App\Utility\EmployeeUtility;
use DateInterval;
use DateTime;
use DateTimeInterface;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

/**
 * WorktimePeriod entity
 */
#[ORM\Entity(repositoryClass: WorktimePeriodRepository::class)]
class WorktimePeriod extends AbstractEntity
{

    /**
     * Used for rendering in list
     * NOTE: I know this is bad code. But fuck it, this project is already pretty shitty.
     */
    private static ?self $before = null;

    /**
     * The start time of worktime period
     */
    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?DateTimeInterface $startTime = null;

    /**
     * The end time of worktime period
     */
    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?DateTimeInterface $endTime = null;

    /**
     * The login device
     */
    #[ORM\Column(nullable: true)]
    private ?string $loginDevice = null;

    /**
     * The logout device
     */
    #[ORM\Column(nullable: true)]
    private ?string $logoutDevice = null;

    /**
     * The employee that is refered to this period
     */
    #[ORM\ManyToOne(targetEntity: Employee::class, inversedBy: 'periods')]
    #[ORM\JoinColumn(nullable: false, onDelete: 'cascade')]
    private ?Employee $employee = null;

    /**
     * Special notes about period
     */
    #[ORM\Column(nullable: true)]
    private ?bool $isOvertimeDecrease = null;

    /**
     * Gets the start time of period
     *
     * @return DateTimeInterface|null The start time
     */
    public function getStartTime(): ?DateTimeInterface
    {
        return $this->startTime;
    }

    /**
     * Sets the start time
     *
     * @param float $startTime The new start time
     * @return $this The updated entity
     */
    public function setStartTime(DateTimeInterface $startTime): self
    {
        $this->startTime = $startTime;

        return $this;
    }

    /**
     * Gets the end time
     *
     * @return float|null The end time
     */
    public function getEndTime(): ?DateTimeInterface
    {
        return $this->endTime;
    }

    /**
     * Sets the end time
     *
     * @param float $endTime The new end time
     * @return $this The updated entity
     */
    public function setEndTime(DateTimeInterface $endTime): self
    {
        $this->endTime = $endTime;

        return $this;
    }

    /**
     * Gets the employee
     *
     * @return Employee|null The employee
     */
    public function getEmployee(): ?Employee
    {
        return $this->employee;
    }

    /**
     * Sets the employee
     *
     * @param Employee|null $employee The new employee
     * @return $this The updated entity
     */
    public function setEmployee(?Employee $employee): self
    {
       $this->employee = $employee;
       return $this;
    }

    /**
     * Gets the date as string
     *
     * @return string Date as string
     */
    public function getDate(): string
    {
        return $this->startTime->format('d.m.Y');
    }

    /**
     * Gets the start time as string
     *
     * @return string Start time as string
     */
    public function getStartTimeString(): string
    {
        return $this->startTime->format('H:i');
    }

    /**
     * Gets the end time as string
     *
     * @return string End time as string
     */
    public function getEndTimeString(): string
    {
        if ($this->endTime) {
            return $this->endTime->format('H:i');
        }
        return "-";
    }

    public function getTimeDiff(): string
    {
        /** @var DateInterval $diff */
        $diff = null;
        if ($this->endTime) {
            $diff = $this->startTime->diff($this->endTime);
        } else {
            $diff = $this->startTime->diff(new DateTime());
        }
        $sub = 0;
        $intervalInSeconds = (new DateTime())->setTimeStamp(0)->add($diff)->getTimeStamp();
        $intervalInSeconds -= EmployeeUtility::getBreakSumToSubstract($this, self::$before) * 3600;
        self::$before = $this;
        return (new DateTime())->setTimeStamp($intervalInSeconds-3600)->format('H:i');
    }

    /**
     * Gets the login device
     *
     * @return string|null The device
     */
    public function getLoginDevice(): string
    {
        return $this->loginDevice ?? "-";
    }

    /**
     * Sets the login device
     *
     * @param string|null $device The device
     * @return $this The updated entity
     */
    public function setLoginDevice(?string $device): self
    {
        $this->loginDevice = $device;
        return $this;
    }

    /**
     * Gets the logout device
     *
     * @return string|null The device
     */
    public function getLogoutDevice(): string
    {
        return $this->logoutDevice ?? "-";
    }

    /**
     * Sets the logout device
     *
     * @param string|null $device The device
     * @return $this The updated entity
     */
    public function setLogoutDevice(?string $device): self
    {
        $this->logoutDevice = $device;
        return $this;
    }

    /**
     * Gets wheather overtime decrease
     *
     * @return bool|null Is overtime decrease
     */
    public function isOvertimeDecrease(): ?bool
    {
        return $this->isOvertimeDecrease;
    }

    /**
     * Sets if is overtime decrease
     *
     * @param bool $isDecrease Is decrease
     * @return $this The updated entity
     */
    public function setOvertimeDecrease(bool $isDecrease): self
    {
        $this->isOvertimeDecrease = $isDecrease;
        return $this;
    }
}

templates/employee/create.html.twig
{% extends 'navbarBase.html.twig' %}

{% block body %}
    <div class="container">
        <h1>Mitarbeiter anlegen</h1>
        {% if error %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endif %}
        {{ form(form) }}
    </div>
    <script>
        document.getElementById('employee_targetWorkingPresent').addEventListener('change', (e) => {
            if (e.target.checked) {
                document.getElementById('targetWorkingHoursLabel').style = "display: block";
                document.getElementById('employee_targetWorkingHours').style = "display: block";
                document.getElementById('employee_targetWorkingHours').required = true;
                document.getElementById('targetWorkingTimeBeginLabel').style = "display: block";
                document.getElementById('employee_targetWorkingTimeBegin').style = "display: block";
                document.getElementById('employee_targetWorkingTimeBegin').required = true;
                document.getElementById('targetWorkingTimeEndLabel').style = "display: block";
                document.getElementById('employee_targetWorkingTimeEnd').style = "display: block";
                document.getElementById('employee_targetWorkingTimeEnd').required = true;
            } else {
                document.getElementById('targetWorkingHoursLabel').style = "display: none";
                document.getElementById('employee_targetWorkingHours').style = "display: none";
                document.getElementById('employee_targetWorkingHours').required = false;
                document.getElementById('targetWorkingTimeBeginLabel').style = "display: none";
                document.getElementById('employee_targetWorkingTimeBegin').style = "display: none";
                document.getElementById('employee_targetWorkingTimeBegin').required = false;
                document.getElementById('targetWorkingTimeEndLabel').style = "display: none";
                document.getElementById('employee_targetWorkingTimeEnd').style = "display: none";
                document.getElementById('employee_targetWorkingTimeEnd').required = false;
            }
        })
    </script>
{% endblock %}

templates/employee/details.html.twig
{% extends 'navbarBase.html.twig' %}

{% block body %}
    <div class="container mt-5">
        <h1>{{ employee.getFirstName() }} {{ employee.getLastName() }} ({{ employee.getUsername() }})</h1>
        {% if is_granted('LDAP_ADMIN_ACCESS') %}
            <a class="btn btn-primary" href="{{ path("worktime_specialday_create", {id: employee.getId()}) }}">
                {{ 'actions.createSpecialDay'|trans }}
            </a>
        {% endif %}
        {% if overtimeSum > 0 and employee.isTimeEmployed() and (is_granted('LDAP_ADMIN_ACCESS') or is_granted("LDAP_PERSONAL_STATS_ACCESS")) %}
            <a class="btn btn-primary" href="{{ path("register_overtime_decrease", {id: employee.getId()}) }}">
                {{ 'actions.createOvertimeDecrease'|trans }}
            </a>
        {% endif %}
        {% if is_granted("LDAP_PERSONAL_STATS_ACCESS") %}
            <a class="btn btn-primary" href="{{ path("worktime_specialday_request_create") }}">
                {{ 'actions.createSpecialDayRequest'|trans }}
            </a>
        {% endif %}
        <ul class="nav nav-tabs mt-5">
            <li class="nav-item">
                <a class="nav-link {{ tab == null ? 'active' : ''}}" href="{{ path("employee_details", {id: employee.getId()}) }}">{{ 'tab.general'|trans }}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{ tab == "holiday" ? 'active' : ''}}" href="{{ path("employee_details", {id: employee.getId()}) }}?tab=holiday">{{ 'tab.holiday'|trans }}</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{ tab == "illness" ? 'active' : ''}}" href="{{ path("employee_details", {id: employee.getId()}) }}?tab=illness">{{ 'tab.illness'|trans }}</a>
            </li>
        </ul>
        {% if tab == "holiday" %}
            <div class="mt-2">
                <h1>{{ 'title.holidays'|trans }}</h1>
                <div class="row">
                    <div class="col-md-11">
                        <table class="table">
                            <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">{{ 'table.date'|trans }}</th>
                                <th scope="col">{{ 'table.notes'|trans }}</th>
                                <th scope="col">{{ 'table.actions'|trans }}</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for holiday in holidays %}
                                <tr>
                                    <th scope="row">{{ holiday.getId() }}</th>
                                    <td>{{ holiday.getDateString() }}</td>
                                    <td>{{ holiday.getNotes() }}</td>
                                    <td>
                                        {% if is_granted('LDAP_ADMIN_ACCESS') %}
                                            <a class="btn btn-sm btn-danger" href="{{ path("worktime_specialday_delete", {id: holiday.getId()}) }}">{{ 'actions.delete'|trans }}</a>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="col col-md-1">
                        <ul class="list-group">
                            {% if holidayPeriods|length > 0 %}
                                {% for period in holidayPeriods %}
                                    <li
                                            class="list-group-item {{ period == timePeriod or (timePeriod == null and period == holidayPeriods[0]) ? 'active' : '' }}"
                                            style="width: fit-content; text-wrap: nowrap"
                                    >
                                        <a
                                                type="button"
                                                href="{{ path("employee_details", {id: employee.getId()}) }}?timePeriod={{ period }}&tab=holiday"
                                                style="text-decoration: none"
                                                class="{{ period == timePeriod or (timePeriod == null and period == holidayPeriods[0]) ? 'text-white' : 'text-dark' }}"
                                        >{{ period }}</a>
                                    </li>
                                {% endfor %}
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        {% elseif tab == "illness" %}
            <div class="mt-2">
                <h1>{{ 'title.illnessDays'|trans }}</h1>
                <div class="row">
                    <div class="col-md-11">
                        <table class="table">
                            <thead>
                            <tr>
                                <th scope="col">#</th>
                                <th scope="col">{{ 'table.date'|trans }}</th>
                                <th scope="col">{{ 'table.notes'|trans }}</th>
                                <th scope="col">{{ 'table.actions'|trans }}</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for illnessDay in illnessDays %}
                                <tr>
                                    <th scope="row">{{ illnessDay.getId() }}</th>
                                    <td>{{ illnessDay.getDateString() }}</td>
                                    <td>{{ illnessDay.getNotes() }}</td>
                                    <td>
                                        {% if is_granted('LDAP_ADMIN_ACCESS') %}
                                            <a class="btn btn-sm btn-danger" href="{{ path("worktime_specialday_delete", {id: illnessDay.getId()}) }}">{{ 'actions.delete'|trans }}</a>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="col col-md-1">
                        <ul class="list-group">
                            {% if illnessPeriods|length > 0 %}
                                {% for period in illnessPeriods %}
                                    <li
                                            class="list-group-item {{ period == timePeriod or (timePeriod == null and period == illnessPeriods[0]) ? 'active' : '' }}"
                                            style="width: fit-content; text-wrap: nowrap"
                                    >
                                        <a
                                                type="button"
                                                href="{{ path("employee_details", {id: employee.getId()}) }}?timePeriod={{ period }}&tab=illness"
                                                style="text-decoration: none"
                                                class="{{ period == timePeriod or (timePeriod == null and period == illnessPeriods[0]) ? 'text-white' : 'text-dark' }}"
                                        >{{ period }}</a>
                                    </li>
                                {% endfor %}
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        {% else %}
            <div class="row mt-2">
                <div class="col-md-5">
                    <h3>{{ 'title.generalInformation'|trans }}</h3>
                    <ul>
                        <li><b>{{ 'list.holidays'|trans }}:</b> {{ employee.getHolidays() }}</li>
                        {% if employee.getHolidaysLeft() %}
                            <li><b>{{ 'list.holidaysLeft'|trans }}:</b> {{ employee.getHolidaysLeft() }}</li>
                        {% endif %}
                        {% if employee.getTargetWorkingHours() != null and employee.getTargetWorkingHours() != 0  %}
                            <li><b>{{ 'list.targetHours'|trans }}:</b> {{ employee.getTargetWorkingHours() }}</li>
                            {% if overtimeDisplayable %}
                                <li><b>{{ 'list.overtimeTransfer'|trans }}:</b> {{ overtimeTransfer }}</li>
                                <li><b>{{ 'list.overtimeDecreaseSum'|trans }}:</b> {{ overtimeDecreaseSum }}</li>
                                {% if overtime < 0 %}
                                    <li><b>{{ 'list.worktimeLeft'|trans }}:</b> {{ -overtime }}</li>
                                {% else %}
                                    <li><b>{{ 'list.overtime'|trans }}:</b> {{ overtime }}</li>
                                {% endif %}
                                <li><b>{{ 'list.overtimeTotal'|trans }}:</b> {{ overtimeSum }}</li>
                            {% else %}
                                <div class="alert alert-warning">{{ 'notice.employeeOvertime'|trans }}</div>
                                {% if overtime < 0 %}
                                    <li><b>{{ 'list.worktimeLeft'|trans }}:</b> {{ -overtime }}</li>
                                {% elseif overtime > 0 %}
                                    <li><b>{{ 'list.overtime'|trans }}:</b> {{ overtime }}</li>
                                {% endif %}
                            {% endif %}
                        {% endif %}
                        <li><b>{{ 'list.hoursWorked'|trans }}:</b> {{ timeWorked }}</li>
                    </ul>
                    <h5>{{ 'form.employee.label.workTimes'|trans }}:</h5>
                    {{ component('WorkTimePlan', {worktimes: employee.getConfiguredWorktimes()}) }}
                </div>
                <div class="col col-md-6">
                    <h3>{{ 'list.workTimes'|trans }}</h3>
                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col">#</th>
                            <th scope="col">{{ 'table.date'|trans }}</th>
                            <th scope="col">{{ 'table.startTime'|trans }}</th>
                            <th scope="col">{{ 'table.endTime'|trans }}</th>
                            <th scope="col">{{ 'table.totalTime'|trans }}</th>
                            <th scope="col">{{ 'table.loginFrom'|trans }}</th>
                            <th scope="col">{{ 'table.logoffFrom'|trans }}</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for period in periods %}
                            {% if period.isOvertimeDecrease() %}
                                <tr>
                                    <th scope="row">{{ period.getId() }}</th>
                                    <td>{{ period.getDate() }}</td>
                                    <td>{{ 'messages.overtimeDecrease'|trans }}</td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tr>
                            {% else %}
                                <tr>
                                    <th scope="row">{{ period.getId() }}</th>
                                    <td>{{ period.getDate() }}</td>
                                    <td>{{ period.getStartTimeString() }}</td>
                                    <td>{{ period.getEndTimeString() }}</td>
                                    <td>{{ period.getTimeDiff() }}</td>
                                    <td style="max-width: 105px; overflow: hidden">{{ period.getLoginDevice() }}</td>
                                    <td style="max-width: 105px; overflow: hidden">{{ period.getLogoutDevice() }}</td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="col col-md-1">
                    <ul class="list-group">
                        {% if workTimePeriods|length > 0 %}
                            {% for period in workTimePeriods %}
                                <li
                                        class="list-group-item {{ period == timePeriod or (timePeriod == null and period == workTimePeriods[0]) ? 'active' : '' }}"
                                        style="width: fit-content; text-wrap: nowrap"
                                >
                                    <a
                                            type="button"
                                            href="{{ path("employee_details", {id: employee.getId()}) }}?timePeriod={{ period }}"
                                            style="text-decoration: none"
                                            class="{{ period == timePeriod or (timePeriod == null and period == workTimePeriods[0]) ? 'text-white' : 'text-dark' }}"
                                    >{{ period }}</a>
                                </li>
                            {% endfor %}
                        {% endif %}
                    </ul>
                </div>
            </div>
        {% endif %}
    </div>
{% endblock %}